version: '3'
services:

  hazelcastcaching:
    image: hazelcast/hazelcast:3.11.1
    ports:
      - 5701:5701

  rest-web-service:
    build: .
    ports:
      - 8080:8181
    links:
      - "hazelcastcaching:hazelcast"

